//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("SnippetCacheEntities", "FK_SnippetComment", "Snippet", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SnippetCache.Data.EF4.Model.Snippet), "Comment", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SnippetCache.Data.EF4.Model.Comment), true)]
[assembly: EdmRelationshipAttribute("SnippetCacheEntities", "FK_UserComment", "User", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SnippetCache.Data.EF4.Model.User), "Comment", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SnippetCache.Data.EF4.Model.Comment), true)]
[assembly: EdmRelationshipAttribute("SnippetCacheEntities", "FK_SnippetFile", "Snippet", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SnippetCache.Data.EF4.Model.Snippet), "File", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SnippetCache.Data.EF4.Model.File), true)]
[assembly: EdmRelationshipAttribute("SnippetCacheEntities", "FK_SnippetHyperlink", "Snippet", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SnippetCache.Data.EF4.Model.Snippet), "Hyperlink", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SnippetCache.Data.EF4.Model.Hyperlink), true)]
[assembly: EdmRelationshipAttribute("SnippetCacheEntities", "FK_LanguageSnippet", "Language", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SnippetCache.Data.EF4.Model.Language), "Snippet", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SnippetCache.Data.EF4.Model.Snippet), true)]
[assembly: EdmRelationshipAttribute("SnippetCacheEntities", "FK_NotificationTypeNotification", "NotificationType", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SnippetCache.Data.EF4.Model.NotificationType), "Notification", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SnippetCache.Data.EF4.Model.Notification), true)]
[assembly: EdmRelationshipAttribute("SnippetCacheEntities", "FK_UserNotification", "User", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SnippetCache.Data.EF4.Model.User), "Notification", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SnippetCache.Data.EF4.Model.Notification), true)]
[assembly: EdmRelationshipAttribute("SnippetCacheEntities", "FK_UserSnippet", "User", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SnippetCache.Data.EF4.Model.User), "Snippet", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SnippetCache.Data.EF4.Model.Snippet), true)]

#endregion

namespace SnippetCache.Data.EF4.Model
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class SnippetCacheEntitiesContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new SnippetCacheEntitiesContainer object using the connection string found in the 'SnippetCacheEntitiesContainer' section of the application configuration file.
        /// </summary>
        public SnippetCacheEntitiesContainer() : base("name=SnippetCacheEntitiesContainer", "SnippetCacheEntitiesContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SnippetCacheEntitiesContainer object.
        /// </summary>
        public SnippetCacheEntitiesContainer(string connectionString) : base(connectionString, "SnippetCacheEntitiesContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SnippetCacheEntitiesContainer object.
        /// </summary>
        public SnippetCacheEntitiesContainer(EntityConnection connection) : base(connection, "SnippetCacheEntitiesContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Comment> Comments
        {
            get
            {
                if ((_Comments == null))
                {
                    _Comments = base.CreateObjectSet<Comment>("Comments");
                }
                return _Comments;
            }
        }
        private ObjectSet<Comment> _Comments;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<File> Files
        {
            get
            {
                if ((_Files == null))
                {
                    _Files = base.CreateObjectSet<File>("Files");
                }
                return _Files;
            }
        }
        private ObjectSet<File> _Files;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Hyperlink> Hyperlinks
        {
            get
            {
                if ((_Hyperlinks == null))
                {
                    _Hyperlinks = base.CreateObjectSet<Hyperlink>("Hyperlinks");
                }
                return _Hyperlinks;
            }
        }
        private ObjectSet<Hyperlink> _Hyperlinks;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Language> Languages
        {
            get
            {
                if ((_Languages == null))
                {
                    _Languages = base.CreateObjectSet<Language>("Languages");
                }
                return _Languages;
            }
        }
        private ObjectSet<Language> _Languages;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Notification> Notifications
        {
            get
            {
                if ((_Notifications == null))
                {
                    _Notifications = base.CreateObjectSet<Notification>("Notifications");
                }
                return _Notifications;
            }
        }
        private ObjectSet<Notification> _Notifications;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<NotificationType> NotificationTypes
        {
            get
            {
                if ((_NotificationTypes == null))
                {
                    _NotificationTypes = base.CreateObjectSet<NotificationType>("NotificationTypes");
                }
                return _NotificationTypes;
            }
        }
        private ObjectSet<NotificationType> _NotificationTypes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Snippet> Snippets
        {
            get
            {
                if ((_Snippets == null))
                {
                    _Snippets = base.CreateObjectSet<Snippet>("Snippets");
                }
                return _Snippets;
            }
        }
        private ObjectSet<Snippet> _Snippets;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<User> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<User>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<User> _Users;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Comments EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToComments(Comment comment)
        {
            base.AddObject("Comments", comment);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Files EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFiles(File file)
        {
            base.AddObject("Files", file);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Hyperlinks EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToHyperlinks(Hyperlink hyperlink)
        {
            base.AddObject("Hyperlinks", hyperlink);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Languages EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLanguages(Language language)
        {
            base.AddObject("Languages", language);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Notifications EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToNotifications(Notification notification)
        {
            base.AddObject("Notifications", notification);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the NotificationTypes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToNotificationTypes(NotificationType notificationType)
        {
            base.AddObject("NotificationTypes", notificationType);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Snippets EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSnippets(Snippet snippet)
        {
            base.AddObject("Snippets", snippet);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsers(User user)
        {
            base.AddObject("Users", user);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SnippetCacheEntities", Name="Comment")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Comment : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Comment object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="text">Initial value of the Text property.</param>
        /// <param name="lastModified">Initial value of the LastModified property.</param>
        /// <param name="snippet_Id">Initial value of the Snippet_Id property.</param>
        /// <param name="user_Id">Initial value of the User_Id property.</param>
        /// <param name="user_FormsAuthId">Initial value of the User_FormsAuthId property.</param>
        public static Comment CreateComment(global::System.Int32 id, global::System.String text, global::System.DateTime lastModified, global::System.Int32 snippet_Id, global::System.Int32 user_Id, global::System.Guid user_FormsAuthId)
        {
            Comment comment = new Comment();
            comment.Id = id;
            comment.Text = text;
            comment.LastModified = lastModified;
            comment.Snippet_Id = snippet_Id;
            comment.User_Id = user_Id;
            comment.User_FormsAuthId = user_FormsAuthId;
            return comment;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Text
        {
            get
            {
                return _Text;
            }
            set
            {
                OnTextChanging(value);
                ReportPropertyChanging("Text");
                _Text = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Text");
                OnTextChanged();
            }
        }
        private global::System.String _Text;
        partial void OnTextChanging(global::System.String value);
        partial void OnTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LastModified
        {
            get
            {
                return _LastModified;
            }
            set
            {
                OnLastModifiedChanging(value);
                ReportPropertyChanging("LastModified");
                _LastModified = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastModified");
                OnLastModifiedChanged();
            }
        }
        private global::System.DateTime _LastModified;
        partial void OnLastModifiedChanging(global::System.DateTime value);
        partial void OnLastModifiedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Snippet_Id
        {
            get
            {
                return _Snippet_Id;
            }
            set
            {
                OnSnippet_IdChanging(value);
                ReportPropertyChanging("Snippet_Id");
                _Snippet_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Snippet_Id");
                OnSnippet_IdChanged();
            }
        }
        private global::System.Int32 _Snippet_Id;
        partial void OnSnippet_IdChanging(global::System.Int32 value);
        partial void OnSnippet_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 User_Id
        {
            get
            {
                return _User_Id;
            }
            set
            {
                OnUser_IdChanging(value);
                ReportPropertyChanging("User_Id");
                _User_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("User_Id");
                OnUser_IdChanged();
            }
        }
        private global::System.Int32 _User_Id;
        partial void OnUser_IdChanging(global::System.Int32 value);
        partial void OnUser_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid User_FormsAuthId
        {
            get
            {
                return _User_FormsAuthId;
            }
            set
            {
                OnUser_FormsAuthIdChanging(value);
                ReportPropertyChanging("User_FormsAuthId");
                _User_FormsAuthId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("User_FormsAuthId");
                OnUser_FormsAuthIdChanged();
            }
        }
        private global::System.Guid _User_FormsAuthId;
        partial void OnUser_FormsAuthIdChanging(global::System.Guid value);
        partial void OnUser_FormsAuthIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SnippetCacheEntities", "FK_SnippetComment", "Snippet")]
        public Snippet Snippet
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Snippet>("SnippetCacheEntities.FK_SnippetComment", "Snippet").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Snippet>("SnippetCacheEntities.FK_SnippetComment", "Snippet").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Snippet> SnippetReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Snippet>("SnippetCacheEntities.FK_SnippetComment", "Snippet");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Snippet>("SnippetCacheEntities.FK_SnippetComment", "Snippet", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SnippetCacheEntities", "FK_UserComment", "User")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("SnippetCacheEntities.FK_UserComment", "User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("SnippetCacheEntities.FK_UserComment", "User").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("SnippetCacheEntities.FK_UserComment", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("SnippetCacheEntities.FK_UserComment", "User", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SnippetCacheEntities", Name="File")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class File : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new File object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="data">Initial value of the Data property.</param>
        /// <param name="lastModified">Initial value of the LastModified property.</param>
        /// <param name="snippet_Id">Initial value of the Snippet_Id property.</param>
        public static File CreateFile(global::System.Int32 id, global::System.String name, global::System.Byte[] data, global::System.DateTime lastModified, global::System.Int32 snippet_Id)
        {
            File file = new File();
            file.Id = id;
            file.Name = name;
            file.Data = data;
            file.LastModified = lastModified;
            file.Snippet_Id = snippet_Id;
            return file;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] Data
        {
            get
            {
                return StructuralObject.GetValidValue(_Data);
            }
            set
            {
                OnDataChanging(value);
                ReportPropertyChanging("Data");
                _Data = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Data");
                OnDataChanged();
            }
        }
        private global::System.Byte[] _Data;
        partial void OnDataChanging(global::System.Byte[] value);
        partial void OnDataChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LastModified
        {
            get
            {
                return _LastModified;
            }
            set
            {
                OnLastModifiedChanging(value);
                ReportPropertyChanging("LastModified");
                _LastModified = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastModified");
                OnLastModifiedChanged();
            }
        }
        private global::System.DateTime _LastModified;
        partial void OnLastModifiedChanging(global::System.DateTime value);
        partial void OnLastModifiedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Snippet_Id
        {
            get
            {
                return _Snippet_Id;
            }
            set
            {
                OnSnippet_IdChanging(value);
                ReportPropertyChanging("Snippet_Id");
                _Snippet_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Snippet_Id");
                OnSnippet_IdChanged();
            }
        }
        private global::System.Int32 _Snippet_Id;
        partial void OnSnippet_IdChanging(global::System.Int32 value);
        partial void OnSnippet_IdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SnippetCacheEntities", "FK_SnippetFile", "Snippet")]
        public Snippet Snippet
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Snippet>("SnippetCacheEntities.FK_SnippetFile", "Snippet").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Snippet>("SnippetCacheEntities.FK_SnippetFile", "Snippet").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Snippet> SnippetReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Snippet>("SnippetCacheEntities.FK_SnippetFile", "Snippet");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Snippet>("SnippetCacheEntities.FK_SnippetFile", "Snippet", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SnippetCacheEntities", Name="Hyperlink")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Hyperlink : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Hyperlink object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="uri">Initial value of the Uri property.</param>
        /// <param name="lastModified">Initial value of the LastModified property.</param>
        /// <param name="snippet_Id">Initial value of the Snippet_Id property.</param>
        public static Hyperlink CreateHyperlink(global::System.Int32 id, global::System.String uri, global::System.DateTime lastModified, global::System.Int32 snippet_Id)
        {
            Hyperlink hyperlink = new Hyperlink();
            hyperlink.Id = id;
            hyperlink.Uri = uri;
            hyperlink.LastModified = lastModified;
            hyperlink.Snippet_Id = snippet_Id;
            return hyperlink;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Uri
        {
            get
            {
                return _Uri;
            }
            set
            {
                OnUriChanging(value);
                ReportPropertyChanging("Uri");
                _Uri = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Uri");
                OnUriChanged();
            }
        }
        private global::System.String _Uri;
        partial void OnUriChanging(global::System.String value);
        partial void OnUriChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LastModified
        {
            get
            {
                return _LastModified;
            }
            set
            {
                OnLastModifiedChanging(value);
                ReportPropertyChanging("LastModified");
                _LastModified = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastModified");
                OnLastModifiedChanged();
            }
        }
        private global::System.DateTime _LastModified;
        partial void OnLastModifiedChanging(global::System.DateTime value);
        partial void OnLastModifiedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Snippet_Id
        {
            get
            {
                return _Snippet_Id;
            }
            set
            {
                OnSnippet_IdChanging(value);
                ReportPropertyChanging("Snippet_Id");
                _Snippet_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Snippet_Id");
                OnSnippet_IdChanged();
            }
        }
        private global::System.Int32 _Snippet_Id;
        partial void OnSnippet_IdChanging(global::System.Int32 value);
        partial void OnSnippet_IdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SnippetCacheEntities", "FK_SnippetHyperlink", "Snippet")]
        public Snippet Snippet
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Snippet>("SnippetCacheEntities.FK_SnippetHyperlink", "Snippet").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Snippet>("SnippetCacheEntities.FK_SnippetHyperlink", "Snippet").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Snippet> SnippetReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Snippet>("SnippetCacheEntities.FK_SnippetHyperlink", "Snippet");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Snippet>("SnippetCacheEntities.FK_SnippetHyperlink", "Snippet", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SnippetCacheEntities", Name="Language")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Language : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Language object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static Language CreateLanguage(global::System.Int32 id, global::System.String name)
        {
            Language language = new Language();
            language.Id = id;
            language.Name = name;
            return language;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SnippetCacheEntities", "FK_LanguageSnippet", "Snippet")]
        public EntityCollection<Snippet> Snippets
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Snippet>("SnippetCacheEntities.FK_LanguageSnippet", "Snippet");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Snippet>("SnippetCacheEntities.FK_LanguageSnippet", "Snippet", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SnippetCacheEntities", Name="Notification")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Notification : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Notification object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="dateCreated">Initial value of the DateCreated property.</param>
        /// <param name="text">Initial value of the Text property.</param>
        /// <param name="notificationType_Id">Initial value of the NotificationType_Id property.</param>
        /// <param name="user_Id">Initial value of the User_Id property.</param>
        /// <param name="user_FormsAuthId">Initial value of the User_FormsAuthId property.</param>
        public static Notification CreateNotification(global::System.Int32 id, global::System.DateTime dateCreated, global::System.String text, global::System.Int32 notificationType_Id, global::System.Int32 user_Id, global::System.Guid user_FormsAuthId)
        {
            Notification notification = new Notification();
            notification.Id = id;
            notification.DateCreated = dateCreated;
            notification.Text = text;
            notification.NotificationType_Id = notificationType_Id;
            notification.User_Id = user_Id;
            notification.User_FormsAuthId = user_FormsAuthId;
            return notification;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateCreated
        {
            get
            {
                return _DateCreated;
            }
            set
            {
                OnDateCreatedChanging(value);
                ReportPropertyChanging("DateCreated");
                _DateCreated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateCreated");
                OnDateCreatedChanged();
            }
        }
        private global::System.DateTime _DateCreated;
        partial void OnDateCreatedChanging(global::System.DateTime value);
        partial void OnDateCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Text
        {
            get
            {
                return _Text;
            }
            set
            {
                OnTextChanging(value);
                ReportPropertyChanging("Text");
                _Text = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Text");
                OnTextChanged();
            }
        }
        private global::System.String _Text;
        partial void OnTextChanging(global::System.String value);
        partial void OnTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 NotificationType_Id
        {
            get
            {
                return _NotificationType_Id;
            }
            set
            {
                OnNotificationType_IdChanging(value);
                ReportPropertyChanging("NotificationType_Id");
                _NotificationType_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NotificationType_Id");
                OnNotificationType_IdChanged();
            }
        }
        private global::System.Int32 _NotificationType_Id;
        partial void OnNotificationType_IdChanging(global::System.Int32 value);
        partial void OnNotificationType_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 User_Id
        {
            get
            {
                return _User_Id;
            }
            set
            {
                OnUser_IdChanging(value);
                ReportPropertyChanging("User_Id");
                _User_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("User_Id");
                OnUser_IdChanged();
            }
        }
        private global::System.Int32 _User_Id;
        partial void OnUser_IdChanging(global::System.Int32 value);
        partial void OnUser_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid User_FormsAuthId
        {
            get
            {
                return _User_FormsAuthId;
            }
            set
            {
                OnUser_FormsAuthIdChanging(value);
                ReportPropertyChanging("User_FormsAuthId");
                _User_FormsAuthId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("User_FormsAuthId");
                OnUser_FormsAuthIdChanged();
            }
        }
        private global::System.Guid _User_FormsAuthId;
        partial void OnUser_FormsAuthIdChanging(global::System.Guid value);
        partial void OnUser_FormsAuthIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SnippetCacheEntities", "FK_NotificationTypeNotification", "NotificationType")]
        public NotificationType NotificationType
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<NotificationType>("SnippetCacheEntities.FK_NotificationTypeNotification", "NotificationType").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<NotificationType>("SnippetCacheEntities.FK_NotificationTypeNotification", "NotificationType").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<NotificationType> NotificationTypeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<NotificationType>("SnippetCacheEntities.FK_NotificationTypeNotification", "NotificationType");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<NotificationType>("SnippetCacheEntities.FK_NotificationTypeNotification", "NotificationType", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SnippetCacheEntities", "FK_UserNotification", "User")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("SnippetCacheEntities.FK_UserNotification", "User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("SnippetCacheEntities.FK_UserNotification", "User").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("SnippetCacheEntities.FK_UserNotification", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("SnippetCacheEntities.FK_UserNotification", "User", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SnippetCacheEntities", Name="NotificationType")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class NotificationType : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new NotificationType object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        public static NotificationType CreateNotificationType(global::System.Int32 id, global::System.String name, global::System.String description)
        {
            NotificationType notificationType = new NotificationType();
            notificationType.Id = id;
            notificationType.Name = name;
            notificationType.Description = description;
            return notificationType;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SnippetCacheEntities", "FK_NotificationTypeNotification", "Notification")]
        public EntityCollection<Notification> Notifications
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Notification>("SnippetCacheEntities.FK_NotificationTypeNotification", "Notification");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Notification>("SnippetCacheEntities.FK_NotificationTypeNotification", "Notification", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SnippetCacheEntities", Name="Snippet")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Snippet : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Snippet object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="guid">Initial value of the Guid property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="previewData">Initial value of the PreviewData property.</param>
        /// <param name="data">Initial value of the Data property.</param>
        /// <param name="lastModified">Initial value of the LastModified property.</param>
        /// <param name="isPublic">Initial value of the IsPublic property.</param>
        /// <param name="language_Id">Initial value of the Language_Id property.</param>
        /// <param name="user_Id">Initial value of the User_Id property.</param>
        /// <param name="user_FormsAuthId">Initial value of the User_FormsAuthId property.</param>
        public static Snippet CreateSnippet(global::System.Int32 id, global::System.Guid guid, global::System.String name, global::System.Byte[] previewData, global::System.Byte[] data, global::System.DateTime lastModified, global::System.Boolean isPublic, global::System.Int32 language_Id, global::System.Int32 user_Id, global::System.Guid user_FormsAuthId)
        {
            Snippet snippet = new Snippet();
            snippet.Id = id;
            snippet.Guid = guid;
            snippet.Name = name;
            snippet.PreviewData = previewData;
            snippet.Data = data;
            snippet.LastModified = lastModified;
            snippet.IsPublic = isPublic;
            snippet.Language_Id = language_Id;
            snippet.User_Id = user_Id;
            snippet.User_FormsAuthId = user_FormsAuthId;
            return snippet;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Guid
        {
            get
            {
                return _Guid;
            }
            set
            {
                OnGuidChanging(value);
                ReportPropertyChanging("Guid");
                _Guid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Guid");
                OnGuidChanged();
            }
        }
        private global::System.Guid _Guid;
        partial void OnGuidChanging(global::System.Guid value);
        partial void OnGuidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] PreviewData
        {
            get
            {
                return StructuralObject.GetValidValue(_PreviewData);
            }
            set
            {
                OnPreviewDataChanging(value);
                ReportPropertyChanging("PreviewData");
                _PreviewData = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PreviewData");
                OnPreviewDataChanged();
            }
        }
        private global::System.Byte[] _PreviewData;
        partial void OnPreviewDataChanging(global::System.Byte[] value);
        partial void OnPreviewDataChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] Data
        {
            get
            {
                return StructuralObject.GetValidValue(_Data);
            }
            set
            {
                OnDataChanging(value);
                ReportPropertyChanging("Data");
                _Data = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Data");
                OnDataChanged();
            }
        }
        private global::System.Byte[] _Data;
        partial void OnDataChanging(global::System.Byte[] value);
        partial void OnDataChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LastModified
        {
            get
            {
                return _LastModified;
            }
            set
            {
                OnLastModifiedChanging(value);
                ReportPropertyChanging("LastModified");
                _LastModified = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastModified");
                OnLastModifiedChanged();
            }
        }
        private global::System.DateTime _LastModified;
        partial void OnLastModifiedChanging(global::System.DateTime value);
        partial void OnLastModifiedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsPublic
        {
            get
            {
                return _IsPublic;
            }
            set
            {
                OnIsPublicChanging(value);
                ReportPropertyChanging("IsPublic");
                _IsPublic = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsPublic");
                OnIsPublicChanged();
            }
        }
        private global::System.Boolean _IsPublic;
        partial void OnIsPublicChanging(global::System.Boolean value);
        partial void OnIsPublicChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Language_Id
        {
            get
            {
                return _Language_Id;
            }
            set
            {
                OnLanguage_IdChanging(value);
                ReportPropertyChanging("Language_Id");
                _Language_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Language_Id");
                OnLanguage_IdChanged();
            }
        }
        private global::System.Int32 _Language_Id;
        partial void OnLanguage_IdChanging(global::System.Int32 value);
        partial void OnLanguage_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 User_Id
        {
            get
            {
                return _User_Id;
            }
            set
            {
                OnUser_IdChanging(value);
                ReportPropertyChanging("User_Id");
                _User_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("User_Id");
                OnUser_IdChanged();
            }
        }
        private global::System.Int32 _User_Id;
        partial void OnUser_IdChanging(global::System.Int32 value);
        partial void OnUser_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid User_FormsAuthId
        {
            get
            {
                return _User_FormsAuthId;
            }
            set
            {
                OnUser_FormsAuthIdChanging(value);
                ReportPropertyChanging("User_FormsAuthId");
                _User_FormsAuthId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("User_FormsAuthId");
                OnUser_FormsAuthIdChanged();
            }
        }
        private global::System.Guid _User_FormsAuthId;
        partial void OnUser_FormsAuthIdChanging(global::System.Guid value);
        partial void OnUser_FormsAuthIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SnippetCacheEntities", "FK_SnippetComment", "Comment")]
        public EntityCollection<Comment> Comments
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Comment>("SnippetCacheEntities.FK_SnippetComment", "Comment");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Comment>("SnippetCacheEntities.FK_SnippetComment", "Comment", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SnippetCacheEntities", "FK_SnippetFile", "File")]
        public EntityCollection<File> Files
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<File>("SnippetCacheEntities.FK_SnippetFile", "File");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<File>("SnippetCacheEntities.FK_SnippetFile", "File", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SnippetCacheEntities", "FK_SnippetHyperlink", "Hyperlink")]
        public EntityCollection<Hyperlink> Hyperlinks
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Hyperlink>("SnippetCacheEntities.FK_SnippetHyperlink", "Hyperlink");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Hyperlink>("SnippetCacheEntities.FK_SnippetHyperlink", "Hyperlink", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SnippetCacheEntities", "FK_LanguageSnippet", "Language")]
        public Language Language
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Language>("SnippetCacheEntities.FK_LanguageSnippet", "Language").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Language>("SnippetCacheEntities.FK_LanguageSnippet", "Language").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Language> LanguageReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Language>("SnippetCacheEntities.FK_LanguageSnippet", "Language");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Language>("SnippetCacheEntities.FK_LanguageSnippet", "Language", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SnippetCacheEntities", "FK_UserSnippet", "User")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("SnippetCacheEntities.FK_UserSnippet", "User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("SnippetCacheEntities.FK_UserSnippet", "User").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("SnippetCacheEntities.FK_UserSnippet", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("SnippetCacheEntities.FK_UserSnippet", "User", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SnippetCacheEntities", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="formsAuthId">Initial value of the FormsAuthId property.</param>
        /// <param name="loginName">Initial value of the LoginName property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        public static User CreateUser(global::System.Int32 id, global::System.Guid formsAuthId, global::System.String loginName, global::System.String email)
        {
            User user = new User();
            user.Id = id;
            user.FormsAuthId = formsAuthId;
            user.LoginName = loginName;
            user.Email = email;
            return user;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid FormsAuthId
        {
            get
            {
                return _FormsAuthId;
            }
            set
            {
                if (_FormsAuthId != value)
                {
                    OnFormsAuthIdChanging(value);
                    ReportPropertyChanging("FormsAuthId");
                    _FormsAuthId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("FormsAuthId");
                    OnFormsAuthIdChanged();
                }
            }
        }
        private global::System.Guid _FormsAuthId;
        partial void OnFormsAuthIdChanging(global::System.Guid value);
        partial void OnFormsAuthIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LoginName
        {
            get
            {
                return _LoginName;
            }
            set
            {
                OnLoginNameChanging(value);
                ReportPropertyChanging("LoginName");
                _LoginName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LoginName");
                OnLoginNameChanged();
            }
        }
        private global::System.String _LoginName;
        partial void OnLoginNameChanging(global::System.String value);
        partial void OnLoginNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] AvatarImage
        {
            get
            {
                return StructuralObject.GetValidValue(_AvatarImage);
            }
            set
            {
                OnAvatarImageChanging(value);
                ReportPropertyChanging("AvatarImage");
                _AvatarImage = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AvatarImage");
                OnAvatarImageChanged();
            }
        }
        private global::System.Byte[] _AvatarImage;
        partial void OnAvatarImageChanging(global::System.Byte[] value);
        partial void OnAvatarImageChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SnippetCacheEntities", "FK_UserComment", "Comment")]
        public EntityCollection<Comment> Comments
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Comment>("SnippetCacheEntities.FK_UserComment", "Comment");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Comment>("SnippetCacheEntities.FK_UserComment", "Comment", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SnippetCacheEntities", "FK_UserNotification", "Notification")]
        public EntityCollection<Notification> Notifications
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Notification>("SnippetCacheEntities.FK_UserNotification", "Notification");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Notification>("SnippetCacheEntities.FK_UserNotification", "Notification", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SnippetCacheEntities", "FK_UserSnippet", "Snippet")]
        public EntityCollection<Snippet> Snippets
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Snippet>("SnippetCacheEntities.FK_UserSnippet", "Snippet");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Snippet>("SnippetCacheEntities.FK_UserSnippet", "Snippet", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
